# Generated by Django 3.2.16 on 2023-08-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20230828_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.CharField(max_length=100, verbose_name='Yayın Tarihi'),
        ),
    ]
